export const student = [
    {id: 1, name: "Mirziyod", age: 19, address: "Samarqand, Uzbekistan", status: "Student", nickname: "ziyoWorld", univ: "minsk", job: "developper", edit: "Edit"},
    {id: 2, name: "Mirziyod", age: 19, address: "Samarqand, Uzbekistan", status: "Student", nickname: "ziyoWorld", univ: "minsk", job: "developper", edit: "Edit"},
    {id: 3, name: "Mirziyod", age: 19, address: "Samarqand, Uzbekistan", status: "Student", nickname: "ziyoWorld", univ: "minsk", job: "developper", edit: "Edit"},
    {id: 4, name: "Mirziyod", age: 19, address: "Samarqand, Uzbekistan", status: "Student", nickname: "ziyoWorld", univ: "minsk", job: "developper", edit: "Edit"},
    {id: 5, name: "Mirziyod", age: 19, address: "Samarqand, Uzbekistan", status: "Student", nickname: "ziyoWorld", univ: "minsk", job: "developper", edit: "Edit"},
    {id: 6, name: "Mirziyod", age: 19, address: "Samarqand, Uzbekistan", status: "Student", nickname: "ziyoWorld", univ: "minsk", job: "developper", edit: "Edit"},
    {id: 7, name: "Mirziyod", age: 19, address: "Samarqand, Uzbekistan", status: "Student", nickname: "ziyoWorld", univ: "minsk", job: "developper", edit: "Edit"},
    {id: 8, name: "Mirziyod", age: 19, address: "Samarqand, Uzbekistan", status: "Student", nickname: "ziyoWorld", univ: "minsk", job: "developper", edit: "Edit"},
    {id: 9, name: "Mirziyod", age: 19, address: "Samarqand, Uzbekistan", status: "Student", nickname: "ziyoWorld", univ: "minsk", job: "developper", edit: "Edit"},
    {id: 10, name: "Mirziyod", age: 19, address: "Samarqand, Uzbekistan", status: "Student", nickname: "ziyoWorld", univ: "minsk", job: "developper", edit: "Edit"},
    {id: 11, name: "Mirziyod", age: 19, address: "Samarqand, Uzbekistan", status: "Student", nickname: "ziyoWorld", univ: "minsk", job: "developper", edit: "Edit"},
    {id: 12, name: "Mirziyod", age: 19, address: "Samarqand, Uzbekistan", status: "Student", nickname: "ziyoWorld", univ: "minsk", job: "developper", edit: "Edit"},
    {id: 13, name: "Mirziyod", age: 19, address: "Samarqand, Uzbekistan", status: "Student", nickname: "ziyoWorld", univ: "minsk", job: "developper", edit: "Edit"},
    {id: 14, name: "Mirziyod", age: 19, address: "Samarqand, Uzbekistan", status: "Student", nickname: "ziyoWorld", univ: "minsk", job: "developper", edit: "Edit"},
    {id: 15, name: "Mirziyod", age: 19, address: "Samarqand, Uzbekistan", status: "Student", nickname: "ziyoWorld", univ: "minsk", job: "developper", edit: "Edit"},
    {id: 16, name: "Mirziyod", age: 19, address: "Samarqand, Uzbekistan", status: "Student", nickname: "ziyoWorld", univ: "minsk", job: "developper", edit: "Edit"},
    {id: 17, name: "Mirziyod", age: 19, address: "Samarqand, Uzbekistan", status: "Student", nickname: "ziyoWorld", univ: "minsk", job: "developper", edit: "Edit"},
    {id: 18, name: "Mirziyod", age: 19, address: "Samarqand, Uzbekistan", status: "Student", nickname: "ziyoWorld", univ: "minsk", job: "developper", edit: "Edit"},
]